// Data jugadores LUB
const jugadores = [
  // Aguada
  {
    nombre: "Marcos Mata",
    imagen: "images/marcosmata.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: [""],
    posicion: "AL",
    posicionNumero: 3,
    altura: 202,
    numero: 6,
    edad: 35,
    extranjero: "Si"
  },
  {
    nombre: "Sebastian Izaguirre",
    imagen: "images/sebastianizaguirre.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: ["Paysandú", "Trouville", "Hebraica y Macabi", "Bohemios", "Capitol", "Defensor Sporting", "Unión Atlética"],
    posicion: "AP",
    posicionNumero: 4,
    altura: 207,
    numero: 10,
    edad: 36,
    extranjero: "No"
  },
  {
    nombre: "Leandro Garcia Morales",
    imagen: "images/leandrogarciamorales.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: ["Biguá", "Hebraica y Macabi"],
    posicion: "ES",
    posicionNumero: 2,
    altura: 188,
    numero: 100,
    edad: 41,
    extranjero: "No"
  },
  {
    nombre: "Mathias Calfani",
    imagen: "images/mathiascalfani.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: ["Biguá", "Malvín"],
    posicion: "AP",
    posicionNumero: 4,
    altura: 202,
    numero: 21,
    edad: 30,
    extranjero: "No"
  },
  {
    nombre: "Federico Bavosi",
    imagen: "images/federicobavosi.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: ["Unión Atlética", "Malvín"],
    posicion: "B",
    posicionNumero: 1,
    altura: 190,
    numero: 22,
    edad: 41,
    extranjero: "No"
  },
  {
    nombre: "Tyreek Duren",
    imagen: "images/tyreekduren.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: [""],
    posicion: "B",
    posicionNumero: 1,
    altura: 183,
    numero: 23,
    edad: 30,
    extranjero: "Si"
  },
  {
    nombre: "Federico Pereiras",
    imagen: "images/federicopereiras.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: ["Biguá", "Capitol", ""],
    posicion: "ES",
    posicionNumero: 2,
    altura: 190,
    numero: 24,
    edad: 27,
    extranjero: "No"
  },
  {
    nombre: "Lucas Silva",
    imagen: "images/lucassilva.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: [""],
    posicion: "AP",
    posicionNumero: 4,
    altura: 197,
    numero: 77,
    edad: 19,
    extranjero: "No"
  },
  {
    nombre: "Chad Posthumus",
    imagen: "images/",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: [""],
    posicion: "P",
    posicionNumero: 5,
    altura: 211,
    numero: 27,
    edad: 31,
    extranjero: "Si"
  },
  // Biguá
  {
    nombre: "Victor Rudd",
    imagen: "images/victorrudd.jpg",
    equipoActual: "Biguá",
    equipoActualAb: "BIG",
    logoEquipo: "images/bigua.png",
    equiposPasado: [""],
    posicion: "AP",
    posicionNumero: 4,
    altura: 206,
    numero: 1,
    edad: 31,
    extranjero: "Si"
  },
  {
    nombre: "Santiago Vidal",
    imagen: "images/santiagovidal.jpg",
    equipoActual: "",
    equipoActualAb: "",
    logoEquipo: "images/bigua.png",
    equiposPasado: ["Larrañaga", "Nacional", "Larre Borges", "Tabaré", "Trouville"],
    posicion: "B",
    posicionNumero: 1,
    altura: 180,
    numero: 4,
    edad: 32,
    extranjero: "No"
  },
  {
    nombre: "Ivan Loriente",
    imagen: "images/ivanloriente.jpg",
    equipoActual: "Biguá",
    equipoActualAb: "BIG",
    logoEquipo: "images/bigua.png",
    equiposPasado: ["Tabaré", "Goes", "Welcome", "Atenas", "Olimpia"],
    posicion: "ES",
    posicionNumero: 2,
    altura: 190,
    numero: 7,
    edad: 29,
    extranjero: "No"
  },
  {
    nombre: "Donald Sims",
    imagen: "images/donaldsims.jpg",
    equipoActual: "Biguá",
    equipoActualAb: "BIG",
    logoEquipo: "images/bigua.png",
    equiposPasado: [""],
    posicion: "ES",
    posicionNumero: 2,
    altura: 190,
    numero: 8,
    edad: 34,
    extranjero: "Si"
  },
  {
    nombre: "Hernan Alvarez",
    imagen: "images/hernanalvarez.jpg",
    equipoActual: "Biguá",
    equipoActualAb: "BIG",
    logoEquipo: "images/bigua.png",
    equiposPasado: [""],
    posicion: "BA",
    posicionNumero: 1,
    altura: 182,
    numero: 13,
    edad: 23,
    extranjero: "No"
  },
  {
    nombre: "Nicolas Andreoli",
    imagen: "images/nicolasandreoli.jpg",
    equipoActual: "Biguá",
    equipoActualAb: "BIG",
    logoEquipo: "images/bigua.png",
    equiposPasado: [""],
    posicion: "AP",
    posicionNumero: 4,
    altura: 197,
    numero: 15,
    edad: 22,
    extranjero: "No"
  },
  {
    nombre: "Luis Santos",
    imagen: "images/luisssantos.jpg",
    equipoActual: "Biguá",
    equipoActualAb: "BIG",
    logoEquipo: "images/bigua.png",
    equiposPasado: [""],
    posicion: "P",
    posicionNumero: 5,
    altura: 203,
    numero: 23,
    edad: 27,
    extranjero: "Si"
  },
  {
    nombre: "Diego Pena Garcia",
    imagen: "images/diegopenagarcia.jpg",
    equipoActual: "Biguá",
    equipoActualAb: "BIG",
    logoEquipo: "images/bigua.png",
    equiposPasado: [""],
    posicion: "AL",
    posicionNumero: 3,
    altura: 195,
    numero: 25,
    edad: 25,
    extranjero: "No"
  },
  {
    nombre: "Alex Lopez",
    imagen: "images/alexlopez.jpg",
    equipoActual: "Biguá",
    equipoActualAb: "BIG",
    logoEquipo: "images/bigua.png",
    equiposPasado: ["Trouville", "Stockolmo", "Sayago", "Marne", "Larre Borges", "Atenas"],
    posicion: "ES",
    posicionNumero: 2,
    altura: 186,
    numero: 31,
    edad: 28,
    extranjero: "No"
  },
  {
    nombre: "Martin Rojas",
    imagen: "images/martinrojas.jpg",
    equipoActual: "Biguá",
    equipoActualAb: "BIG",
    logoEquipo: "images/bigua.png",
    equiposPasado: [""],
    posicion: "AP",
    posicionNumero: 4,
    altura: 194,
    numero: 42,
    edad: 23,
    extranjero: "No"
  },
  // Capitol
  {
    nombre: "Emiliano Bonet",
    imagen: "images/emilianobonet.png",
    equipoActual: "Capitol",
    equipoActualAb: "CAP",
    logoEquipo: "images/capitol.jpg",
    equiposPasado: ["Sayago"],
    posicion: "ES",
    posicionNumero: 2,
    altura: 186,
    numero: 2,
    edad: 20,
    extranjero: "No"
  },
  {
    nombre: "Juan Wenzel",
    imagen: "images/juanwenzel.png",
    equipoActual: "Capitol",
    equipoActualAb: "CAP",
    logoEquipo: "images/capitol.jpg",
    equiposPasado: ["Trouville", "Peñarol"],
    posicion: "AL",
    posicionNumero: 3,
    altura: 191,
    numero: 6,
    edad: 33,
    extranjero: "No"
  },
  {
    nombre: "Claudio Bascou",
    imagen: "images/claudiobascou.jpg",
    equipoActual: "Capitol",
    equipoActualAb: "CAP",
    logoEquipo: "images/capitol.jpg",
    equiposPasado: ["Trouville", "Larre Borges"],
    posicion: "ES",
    posicionNumero: 2,
    altura: 185,
    numero: 8,
    edad: 32,
    extranjero: "No"
  },
  {
    nombre: "Nahuel Amichetti",
    imagen: "images/nahuelamichetti.png",
    equipoActual: "Capitol",
    equipoActualAb: "CAP",
    logoEquipo: "images/capitol.jpg",
    equiposPasado: ["Verdirrojo", "Peñarol"],
    posicion: "AP",
    posicionNumero: 4,
    altura: 202,
    numero: 15,
    edad: 33,
    extranjero: "No"
  },
  {
    nombre: "Marcos Marotta",
    imagen: "images/marcosmarotta.jpg",
    equipoActual: "Capitol",
    equipoActualAb: "CAP",
    logoEquipo: "images/capitol.jpg",
    equiposPasado: ["Welcome", "Montevideo", "Goes", "Bohemios", "Larre Borges", "Trouville", "Cordón"],
    posicion: "B",
    posicionNumero: 1,
    altura: 180,
    numero: 24,
    edad: 33,
    extranjero: "No"
  },
  {
    nombre: "Demian Alvarez",
    imagen: "images/demianalvares.jpg",
    equipoActual: "Capitol",
    equipoActualAb: "CAP",
    logoEquipo: "images/capitol.jpg",
    equiposPasado: ["Sayago", "Defensor Sporting", "Goes", "Larre Borges", "Aguada", "Bigua", "Stockolmo"],
    posicion: "AL",
    posicionNumero: 3,
    altura: 193,
    numero: 41,
    edad: 37,
    extranjero: "No"
  },
  {
    nombre: "Paul Harrison",
    imagen: "images/paulharrison.png",
    equipoActual: "Capitol",
    equipoActualAb: "CAP",
    logoEquipo: "images/capitol.jpg",
    equiposPasado: ["Goes", "Montevideo", "Olimpia", "Sayago", "Trouville", "Larre Borges", "Cordon", "25 de Agosto"],
    posicion: "P",
    posicionNumero: 5,
    altura: 204,
    numero: 50,
    edad: 32,
    extranjero: "Si"
  },
  {
    nombre: "Eduardo Gamboa",
    imagen: "",
    equipoActual: "Capitol",
    equipoActualAb: "CAP",
    logoEquipo: "images/capitol.jpg",
    equiposPasado: [""],
    posicion: "ES",
    posicionNumero: 2,
    altura: 188,
    numero: 0,
    edad: 37,
    extranjero: "Si"
  },
  {
    nombre: "",
    imagen: "images/",
    equipoActual: "Capitol",
    equipoActualAb: "CAP",
    logoEquipo: "images/capitol.jpg",
    equiposPasado: [""],
    posicion: "",
    posicionNumero: ,
    altura: ,
    numero: ,
    edad: ,
    extranjero: ""
  },
]
