// Data jugadores LUB
const jugadores = [
  // Aguada
  {
    nombre: "Juan Ignacio Stoll",
    imagen: "images/juanignaciostoll.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: [""],
    posicion: "B",
    posicionNumero: 1,
    altura: 187,
    numero: 3,
    edad: 18,
    extranjero: "No"
  },
  {
    nombre: "Marcos Mata",
    imagen: "images/marcosmata.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: [""],
    posicion: "AL",
    posicionNumero: 3,
    altura: 202,
    numero: 6,
    edad: 35,
    extranjero: "Si"
  },
  {
    nombre: "Sebastian Izaguirre",
    imagen: "images/sebastianizaguirre.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: ["Paysandú", "Trouville", "Hebraica y Macabi", "Bohemios", "Capitol", "Defensor Sporting", "Unión Atlética"],
    posicion: "AP",
    posicionNumero: 4,
    altura: 207,
    numero: 10,
    edad: 36,
    extranjero: "No"
  },
  {
    nombre: "Leandro Garcia Morales",
    imagen: "images/leandrogarciamorales.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: ["Biguá", "Hebraica y Macabi"],
    posicion: "ES",
    posicionNumero: 2,
    altura: 188,
    numero: 100,
    edad: 41,
    extranjero: "No"
  },
  {
    nombre: "Gabriel Brun",
    imagen: "images/gabrielbrun.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: [""],
    posicion: "B",
    posicionNumero: 1,
    altura: 175,
    numero: 13,
    edad: 18,
    extranjero: "No"
  },
  {
    nombre: "Agustin Gentile",
    imagen: "images/agustingentile.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: [""],
    posicion: "AL",
    posicionNumero: 3,
    altura: 193,
    numero: 14,
    edad: 19,
    extranjero: "No"
  },
  {
    nombre: "Mathias Calfani",
    imagen: "images/mathiascalfani.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: ["Biguá", "Malvín"],
    posicion: "AP",
    posicionNumero: 4,
    altura: 202,
    numero: 21,
    edad: 30,
    extranjero: "No"
  },
  {
    nombre: "Federico Bavosi",
    imagen: "images/federicobavosi.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: ["Unión Atlética", "Malvín"],
    posicion: "B",
    posicionNumero: 1,
    altura: 190,
    numero: 22,
    edad: 41,
    extranjero: "No"
  },
  {
    nombre: "Tyreek Duren",
    imagen: "images/tyreekduren.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: [""],
    posicion: "B",
    posicionNumero: 1,
    altura: 183,
    numero: 23,
    edad: 30,
    extranjero: "Si"
  },
  {
    nombre: "Federico Pereiras",
    imagen: "images/federicopereiras.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: ["Biguá", "Capitol", ""],
    posicion: "ES",
    posicionNumero: 2,
    altura: 190,
    numero: 24,
    edad: 27,
    extranjero: "No"
  },
  {
    nombre: "Joaquin Silveira",
    imagen: "images/joaquinsilveira.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: [""],
    posicion: "AP",
    posicionNumero: 4,
    altura: 195,
    numero: 61,
    edad: 20,
    extranjero: "No"
  },
  {
    nombre: "Lucas Silva",
    imagen: "images/lucassilva.jpg",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: [""],
    posicion: "AP",
    posicionNumero: 4,
    altura: 197,
    numero: 77,
    edad: 19,
    extranjero: "No"
  },
  {
    nombre: "Chad Posthumus",
    imagen: "images/",
    equipoActual: "Aguada",
    equipoActualAb: "AGU",
    logoEquipo: "images/aguada.png",
    equiposPasado: [""],
    posicion: "P",
    posicionNumero: 5,
    altura: 211,
    numero: 27,
    edad: 31,
    extranjero: "Si"
  },
  // Biguá
  // {
  //   nombre: "",
  //   imagen: "images/",
  //   equipoActual: "",
  //   equipoActualAb: "",
  //   logoEquipo: "images/aguada.png",
  //   equiposPasado: [""],
  //   posicion: "",
  //   posicionNumero: ,
  //   altura: ,
  //   numero: ,
  //   edad: ,
  //   extranjero: ""
  // },
  // {
  //   nombre: "",
  //   imagen: "images/",
  //   equipoActual: "",
  //   equipoActualAb: "",
  //   logoEquipo: "images/aguada.png",
  //   equiposPasado: [""],
  //   posicion: "",
  //   posicionNumero: ,
  //   altura: ,
  //   numero: ,
  //   edad: ,
  //   extranjero: ""
  // },
  // {
  //   nombre: "",
  //   imagen: "images/",
  //   equipoActual: "",
  //   equipoActualAb: "",
  //   logoEquipo: "images/aguada.png",
  //   equiposPasado: [""],
  //   posicion: "",
  //   posicionNumero: ,
  //   altura: ,
  //   numero: ,
  //   edad: ,
  //   extranjero: ""
  // },
  // {
  //   nombre: "",
  //   imagen: "images/",
  //   equipoActual: "",
  //   equipoActualAb: "",
  //   logoEquipo: "images/aguada.png",
  //   equiposPasado: [""],
  //   posicion: "",
  //   posicionNumero: ,
  //   altura: ,
  //   numero: ,
  //   edad: ,
  //   extranjero: ""
  // },
]
